Add bookings
drumer32/java-shareit pull request #3
Opened 2022-07-20 13:39 UTC by drumer32

Здравствуйте, Евгений! Вот PR с моей работой.
Единственный момент, в ТЗ было указано, что наша БД PostgreSQL, но тесты все для H2. Как я понял из обсуждений, делать в итоге нужно на H2

2022-07-21 05:05 UTC, EugeneLenkevich requested changes
Привет, Георгий, спасибо за PR

В целом все супер, на учебный код не особо походит :)

1. То что в тестах используется H2 - более чем нормально, обычно так и делают. Единственное, в теории, проблемы могут быть если используется нативный SQL, диалекты которого могут не совпадать, но это не наш случай :)
2. Я отметил несколько моментов, на всем я не настаиваю, если что-то получится то гут, но кроме исправлении названий некоторых переменных :)

2022-07-21 05:05 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getAll(userId).stream().map(item -> {
В данном случае для того чтобы вытащить все данные производится множество запросов к БД, давай попробуем вытащить их одним запросом, связь с comments у тебя уже есть, попробуем выполнить через репозиторий вот такой запрос HQL:

from Item it join fetch it.comments

В этом случае JPA (Hibernate) будет конструировать единый запрос с join нужной таблицы, которая у тебя смаплена как LAZY и, в общем случае, сама по себе загружаться не будет (что тоже верно =)

https://habr.com/ru/company/otus/blog/529692/

2022-07-24 11:19 UTC, drumer32 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getAll(userId).stream().map(item -> {
Попробовал сделать так, но при таком коде: @Query(value = "from Item it join fetch it.comments")
    List<Item> getAllByOwnerId(long userId);

2022-07-24 11:55 UTC, drumer32 commented
Снова здравствуйте! Наконец то добрался до компа. Названия переменных я поменял. а вот с JOIN FETCH возникла проблема. Описал все в комментариях

2022-07-24 16:04 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getAll(userId).stream().map(item -> {
Надо смотреть что там сравнивает постман, не особо хорошо знаком с самими тестами, мы с ними особо не сталкиваемся, мне кажется нам сейчас это не особо критично (можно много времени на это потратить), главное увидеть как можно вытаскивать LAZY-коллекции одним запросом. В таком виде движок хибера делает JOIN таблиц, в то время как по умолчанию он будет для каждой связанной коллекции делать подзапрос, отдельный селект.

Генерируемый sql можно посмотреть включив вот эти проперти (что кстати уже сделано)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

2022-07-24 16:05 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!
При join fetch оставил комментарий :)

2022-07-24 16:07 UTC, drumer32 commented
большое спасибо !

2022-07-24 16:07 UTC, merged